---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: molecule-epel-${TEST_DISTRO:-centos7}-${TEST_INSTANCE_NAME:-1}
    distro: ${TEST_DISTRO:-centos7}
provisioner:
  name: ansible
  options:
    diff: ${TEST_ENABLE_ANSIBLE_DIFF:-true}
    v: ${TEST_ENABLE_ANSIBLE_VERBOSITY:-false}
  config_options:
    defaults:
      stdout_callback: yaml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
  env:
    TEST_DISTRO: ${TEST_DISTRO:-centos7}
